name: "Publish"
description: "Publishes artifacts to GitHub Releases and sends notifications"
inputs:
  target:
    description: "Target Platform"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Run Platform Workflow
      id: get-square
      run: python ${{ inputs.target }}.py
      shell: bash
